version: '3'

services:
    passup_db:
        image: 'mysql:8.0'
        container_name: passup_db
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=passup
            - MYSQL_USER=user
            - MYSQL_PASSWORD=user
        volumes:
            - ./_data/mysql:/var/lib/mysql

    passup_app:
        image: ambientum/php:7.3-nginx
        container_name: passup_app
        volumes:
            - .:/var/www/app
        ports:
            - "8082:8080"
        external_links:
            - passup_db
        environment:
            - APP_ENV=development
            - APP_KEY=base64:CjrQ0MzJsASL1tWlVTZQKvT+HfqVMHe6xXrvLdiLZa8=
            - APP_NAME=UniPass
            - APP_DEBUG=false
            - APP_VERSION=1.0.0
            - QUEUE_CONNECTION=database
            - DB_CONNECTION_ROOT=mysql_root
            - DB_USERNAME_ROOT=root
            - DB_PASSWORD_ROOT=root
            - DB_CONNECTION=mysql_user
            - DB_HOST=passup_db
            - DB_PORT=3306
            - DB_DATABASE=passup
            - DB_USERNAME=user
            - DB_PASSWORD=user
